apiVersion: v1
clusters:
- cluster:
    certificate-authority: k8s-ca.pem
    server: https://k8smaster.i.cchh.io/
  name: west
contexts:
- context:
    cluster: west
    namespace: prod
    user: todd.pierzina
  name: me
current-context: me
kind: Config
preferences: {}
users:
- name: todd.pierzina
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - exec-credential
      - --user=todd.pierzina
      command: k8s-auth
      env: null
      provideClusterInfo: false
