#!/usr/bin/env zsh

export _DOT_SKIP_HOMEBREW_SETUP=1
export _DOT_SKIP_ITERM_SETUP=1
export _DOT_SKIP_PIPENV_SETUP=1
export _DOT_SKIP_RANCHER_DESKTOP_SETUP=1
export _DOT_SKIP_POSTGRES_SETUP=1
export _DOT_SKIP_SDKMAN_SETUP=1

export HOMEBREW_NO_AUTO_UPDATE=1