apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED==
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority: k8s-ca.pem
    server: https://k8smaster.i.cchh.io/
  name: west
contexts:
- context:
    cluster: west
    namespace: dev
    user: todd.pierzina
  name: dev
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: west
    namespace: perf
    user: todd.pierzina
  name: perf
- context:
    cluster: west
    namespace: prod
    user: todd.pierzina
  name: prod
current-context: perf
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED=
- name: todd.pierzina
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - exec-credential
      - --user=todd.pierzina
      command: k8s-auth
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
